### ISSUE TITLE
c = (a * b) - ((b / a) + b) bug

### ISSUE THREAD

**Issue by yrom1** [yrom1/torchy#11]
```c++
[cling]$ Tensor<float> a({1}, {2.0}, true)
(Tensor<float> &) @0x109b60460
[cling]$ Tensor<float> b({1}, {43.0}, true)
(Tensor<float> &) @0x1098ec8e0
[cling]$ auto c = (a * b) - ((b / a) + b)
(Tensor<float> &) @0x109ba0ae0
[cling]$ c.graph()
Tensor@0x109ba0ae0 (-)
  Tensor@0x6000013c1998 (*)
    Tensor@0x6000013c1598
    Tensor@0x6000013c1718
  Tensor@0x6000013c1918 (+)
    Tensor@0x6000013c1798 (/)
      Tensor@0x6000013c1618
      Tensor@0x6000013c1698
    Tensor@0x6000013c1a18
[cling]$ c.backward()
[cling]$ a.autograd_meta_.get()->grad_.storage_.get()->data_
(std::vector<float> &) { 32.2500f }
[cling]$ b.autograd_meta_.get()->grad_.storage_.get()->data_
(std::vector<float> &) { 3.50000f }
```
```py
>>> import torch
>>> a = torch.tensor((2.0), requires_grad=True)
>>> b = torch.tensor((43.0), requires_grad=True)
>>> c = (a * b) - ((b / a) + b)
>>> c.backward()
>>> a.grad
tensor(53.7500)
>>> b.grad
tensor(0.5000)
```

**Comment by yrom1** [comment]
ec7a252584895efb97b54043e2ebfd976ff20241

**Comment by yrom1** [comment]
```cpp
(main) Ryans-Air:torchy ryan$ sh cling.sh 
[cling]$ Tensor<float> a({1}, {4.2}, true)
(Tensor<float> &) @0x107800460
[cling]$ auto c = a * a * a;
[cling]$ c.backward()
[cling]$ c.graph()
Tensor@0x1078246a8 (*)
  Tensor@0x600002d10298 (*)
    Tensor@0x600002d10218
    Tensor@0x600002d10398
  Tensor@0x600002d10318
[cling]$ c.data()
(const std::vector<float> &) { 74.0880f }
[cling]$ c.grad()
(const std::vector<float> &) { 1.00000f }
[cling]$ a.data()
(const std::vector<float> &) { 4.20000f }
[cling]$ a.grad()
(const std::vector<float> &) { 26.0400f }
[cling]$ .q
```
```py
(main) Ryans-Air:torchy ryan$ py
Python 3.11.1 (main, Apr 19 2023, 18:41:42) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
a >>> a = torch.tensor((4.2), requires_grad=True)
>>> c = a * a * a
>>> c.backward()
>>> c.data()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'Tensor' object is not callable
>>> c.data
tensor(74.0880)
>>> c.grad
<stdin>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:491.)
>>> a.data
tensor(4.2000)
>>> a.grad
tensor(52.9200)
```

**Comment by yrom1** [comment]
8 vs 12
```py
(main) Ryans-Air:torchy ryan$ py
Python 3.11.1 (main, Apr 19 2023, 18:41:42) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> a = torch.tensor((2.0), requires_grad=True)
>>> a
tensor(2., requires_grad=True)
>>> c
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'c' is not defined
>>> c = a * a * a
>>> c
tensor(8., grad_fn=<MulBackward0>)
>>> c.data
tensor(8.)
>>> c.grad
<stdin>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:491.)
>>> a
tensor(2., requires_grad=True)
>>> a.grad
>>> c.backward()
>>> a.data
tensor(2.)
>>> a.grad
tensor(12.)
```
```c++
(main) Ryans-Air:torchy ryan$ sh cling.sh 
[cling]$ Tensor<float> a({1}, {2.0}, true);
[cling]$ a
(Tensor<float> &) @0x105a44460
[cling]$ auto c = a * a * a;
[cling]$ c.graph()
Tensor@0x105a6c6a8 (*)
  Tensor@0x600001c69f18 (*)
    Tensor@0x600001c69e98
    Tensor@0x600001c6a018
  Tensor@0x600001c69f98
[cling]$ c.backward()
[cling]$ c.data()
(const std::vector<float> &) { 8.00000f }
[cling]$ c.grad()
(const std::vector<float> &) { 1.00000f }
[cling]$ a.data()
(const std::vector<float> &) { 2.00000f }
[cling]$ a.grad()
(const std::vector<float> &) { 8.00000f }
```

**Comment by yrom1** [comment]
```py
>>> a = torch.tensor((2.0), requires_grad=True)
>>> a
tensor(2., requires_grad=True)
>>> c = a * a
>>> c.backward()
>>> a.data
tensor(2.)
>>> a.grad
tensor(4.)
```
it's something something `4 + (2 * 4)` vs `4 + (2 * 2)`?

**Comment by yrom1** [comment]
```py
(main) Ryans-Air:torchy ryan$ py micrograd_mul_backward.py 
_backward
+= other.data=2.0 out.grad=1
+= self.data=4.0 out.grad=1
_backward
+= other.data=2.0 out.grad=2.0
+= self.data=2.0 out.grad=2.0
a.data=2.0 a.grad=12.0
```
because in mulbackward the numbers are flipped, += self.data=4.0 out.grad=1 means it's for the node that is the bare leaf, not the node that is the result of 2 * 2. so this leaf gets a grad of 4, but the inernal node that is 4 gets a grad of 2. thats why out.grad is 2.0 for the second _backward. so for a, being all the leaf nodes we have 4*1 + (2*2 + 2 *2) = 12

**Comment by yrom1** [comment]
```cpp
[cling]$ ag::t a = ag::tensor({1}, {4.2f})
(ag::t &) std::shared_ptr -> 0x600003030b58
[cling]$ auto c = a * a * a
(std::shared_ptr<ag::Tensor> &) std::shared_ptr -> 0x600003030e58
[cling]$ c.get()->backward()
1
2
3
4
5
6
6
3
[cling]$ a.get()->grad_
(std::vector<float> &) { 52.9200f }
```

**Comment by yrom1** [comment]
```
(main) Ryans-MacBook-Air:torchy ryan$ sh cling.sh 
[cling]$ ag::t a = ag::tensor({1}, {2.0})
(ag::t &) std::shared_ptr -> 0x6000012e0b58
[cling]$ ag::t b = ag::tensor({1}, {43.0})
(ag::t &) std::shared_ptr -> 0x600001284198
[cling]$ a
(ag::t &) std::shared_ptr -> 0x6000012e0b58
[cling]$ b
(ag::t &) std::shared_ptr -> 0x600001284198
[cling]$ auto c = (a * b) - ((b / a) + b)
(std::shared_ptr<ag::Tensor> &) std::shared_ptr -> 0x60000128c258
[cling]$ auto l = c.get()->sum()
(std::shared_ptr<ag::Tensor> &) std::shared_ptr -> 0x6000012e0c18
[cling]$ a.grad
input_line_11:2:3: error: no member named 'grad' in 'std::__1::shared_ptr<ag::Tensor>'; did you mean to
      use '->' instead of '.'?
 a.grad
  ^
  ->
input_line_11:2:4: error: reference to non-static member function must be called; did you mean to call it
      with no arguments?
 a.grad
 ~~^~~~
       ()
./torchy.hpp:97:8: note: possible target for call
  void grad() {
       ^
./torchy.hpp:127:10: note: possible target for call
  float &grad(const std::vector<size_t> &indices) {
         ^
[cling]$ a.get()->grad
input_line_12:2:11: error: reference to non-static member function must be called; did you mean to call it
      with no arguments?
 a.get()->grad
 ~~~~~~~~~^~~~
              ()
./torchy.hpp:97:8: note: possible target for call
  void grad() {
       ^
./torchy.hpp:127:10: note: possible target for call
  float &grad(const std::vector<size_t> &indices) {
         ^
[cling]$ a.get()->grad_
(std::vector<float> &) { 0.00000f }
[cling]$ b.get()->grad_
(std::vector<float> &) { 0.00000f }
[cling]$ l.get()->backward()
21.5
1
2
3
4
5
6
7
5
6
6
6
7
5
6
7
5
6
6
6
[cling]$ a.get()->grad
input_line_16:2:11: error: reference to non-static member function must be called; did you mean to call it
      with no arguments?
 a.get()->grad
 ~~~~~~~~~^~~~
              ()
./torchy.hpp:97:8: note: possible target for call
  void grad() {
       ^
./torchy.hpp:127:10: note: possible target for call
  float &grad(const std::vector<size_t> &indices) {
         ^
[cling]$ a.get()->grad_
(std::vector<float> &) { 53.7500f }
[cling]$ b.get()->grad_
(std::vector<float> &) { 0.500000f }
```
